spring:
  application:
    name: wind-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wind27/wind-config.git #服务的git仓库地址
          search-paths: /config #配置文件所在的目录
          username: qianchun27@hotmail.com #git仓库的用户名
          password: 726377qc #git仓库的密码
          default-label: master #分支名

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://dev.wind.com/eureka/